site_name: Sentenza's notes
site_author: sentenza
repo_url: https://github.com/sentenza/docs
nav:
    - Home: index.md
    # - Scala: scala.md
    - Links: links.md
theme: 
  name: readthedocs
  hljs_languages:
    - scala